-- complexes.status 에 `out_of_region` 을 추가한다 (2026-08-21)
--
-- ── 왜 필요한가 ────────────────────────────────────────────────────────────
-- `realtrade-story` 의 전수 감사(`.planning/inbox/HANDOFF-bds-20260821.md` P1-a)가
-- **운영권역 밖 단지 9곳이 우리 sgg_code 로 들어와 있는 것**을 찾았다. 주소도 좌표도
-- 부산 금정구·북구·사상구·사하구, 창녕군, 양산시, 고성군을 가리킨다. 동명이지 매칭이
-- 만든 것이다.
--
-- 이들을 지도·랭킹·검색에서 빼야 하는데, 기존 enum 6단계 중 맞는 값이 없다:
--
--   pre_sale / under_construction / recently_built / active / in_redevelopment / demolished
--
-- `demolished` 를 쓰면 매칭 RPC 가 걸러주긴 한다(`status != 'demolished'`). 그러나
-- **철거되지 않은 건물을 철거됐다고 기록하는 것**이다. 거짓 사실을 DB 에 남기면
-- 나중에 이 데이터를 보는 사람이 잘못된 결론을 내린다 — 실제로 이 단지들은 멀쩡히
-- 존재하고, 다만 **우리 서비스 권역이 아닐 뿐**이다.
--
-- ── 이 값의 의미 ───────────────────────────────────────────────────────────
-- `out_of_region` = 실재하는 단지이지만 우리 운영권역(regions.is_active) 밖이다.
--   - 지도·랭킹·검색에서 제외한다
--   - 삭제하지 않는다 — 권역이 넓어지면(부산이 2026-08-20 에 그랬듯) 되살릴 수 있다
--   - 붙어 있던 거래는 `complex_id` 를 끊어 미연결로 둔다. 거래 자체는 실재하므로 지우지 않는다
--
-- ⚠️ enum 값 추가는 되돌리기 어렵다(PostgreSQL 은 enum 값 DROP 을 지원하지 않는다).
--    그래서 `demolished` 재사용 대신 새 값을 만드는 판단을 여기 남긴다.
--
-- ⚠️ 소비처 확인: 매칭 RPC 3곳이 `status != 'demolished'` 로 거른다
--    (match_complex_by_admin 0~3단계). 이 조건은 `out_of_region` 을 걸러주지 **않는다.**
--    그러나 P1-a 처리에서 해당 단지의 거래를 모두 끊고 다시 붙지 않게 하는 것이 목적이므로,
--    매칭이 이들을 후보로 삼는 것 자체를 막아야 한다 → 아래에서 조건을 함께 넓힌다.

alter type public.complex_status add value if not exists 'out_of_region';
